services:
  - type: web
    name: thecheck-api
    env: python
    plan: free
    
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3

      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_NAME
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
