services:
  - type: web
    name: thecheck-api
    env: python
    plan: free
    
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.3 # Garanta que esta é a sua versão do Python

      # Para os segredos, apenas definimos a chave.
      # O Render irá solicitar o valor na interface e o armazenará de forma segura.
      - key: DB_USER
      - key: DB_PASSWORD
      - key: DB_HOST
      - key: DB_PORT
      - key: DB_NAME
      - key: JWT_SECRET_KEY
      - key: API_KEY_STORMGLASS